"use client";

import Link from "next/link";
import { ArrowLeft, Calendar } from "lucide-react";

export default function TermsPage() {

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      {/* Header */}
      <header className="border-b border-primary/10 bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <ArrowLeft className="h-5 w-5 text-muted-foreground hover:text-primary transition-colors" />
              <span className="text-sm text-muted-foreground hover:text-primary transition-colors">Back to Home</span>
            </Link>
            <div className="flex items-center gap-2">
              <div className="relative h-8 w-8">
                <img
                  src="/logo-primary.png"
                  alt="Disoriti"
                  className="object-contain h-full w-full"
                />
              </div>
              <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent">
                Disoriti
              </span>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-6 py-12">
        <div className="max-w-6xl mx-auto">
          {/* Title Section */}
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent">
              Terms of Service – Disoriti V.O.F.
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Please read these terms carefully before using our services.
            </p>
            <div className="mt-6 flex items-center justify-center gap-2 text-sm text-muted-foreground">
              <Calendar className="h-4 w-4" />
              <span>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
            </div>
          </div>

          <div className="max-w-3xl mx-auto">
            <div className="bg-background/50 backdrop-blur-sm rounded-2xl border border-primary/10 p-8 shadow-lg space-y-6">
              <p>
                By using our services, you agree to these terms. Please read them carefully.
              </p>

              <h2 className="text-2xl font-semibold">1. Definitions</h2>
              <p>
                <strong>Service</strong>: the AI content generator provided by Disoriti, including all related software, APIs, interfaces, updates, upgrades, and documentation.
              </p>
              <p>
                <strong>User</strong>: any individual or legal entity using the Service.
              </p>
              <p>
                <strong>Content</strong>: all data, text, images, or other materials entered or generated by the User through the Service.
              </p>

              <h2 className="text-2xl font-semibold">2. Services</h2>
              <p>
                Disoriti provides an AI content generator that allows businesses to create advertising content. We offer both a free version and a paid subscription.
              </p>

              <h2 className="text-2xl font-semibold">3. Registration and Account</h2>
              <p>
                To use our Services, you must create an account and provide your email address and Instagram credentials. You are required to: provide accurate and up-to-date information; choose a strong password; keep your login details confidential; immediately notify us of any misuse or unauthorized use.
              </p>
              <p>
                You are responsible for all activities occurring under your account. Disoriti is not liable for unauthorized use if you share your login credentials.
              </p>

              <h2 className="text-2xl font-semibold">4. License</h2>
              <p>
                We grant you a limited, non-exclusive, non-transferable, and revocable right to use the Service for your internal business purposes. It is prohibited to copy, modify, reverse-engineer, decompile, redistribute, or sublicense the software.
              </p>

              <h2 className="text-2xl font-semibold">5. Prohibited Use</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>Upload illegal, harmful, or copyrighted content without permission;</li>
                <li>Use the Service for spam, scraping, hacking, or abuse of APIs;</li>
                <li>Circumvent or attempt to circumvent the Service’s security measures;</li>
                <li>Use the Service in violation of applicable laws.</li>
              </ul>

              <h2 className="text-2xl font-semibold">6. API Use</h2>
              <p>
                Use of our APIs is subject to these Terms and any additional API documentation. We are not liable for any damages or losses resulting from the use of the API by you or by third parties.
              </p>

              <h2 className="text-2xl font-semibold">7. Subscriptions, Payments, and Cancellation</h2>
              <p>
                We offer both free and paid subscriptions. Paid subscriptions are billed in advance according to the pricing listed on our website. Unless otherwise stated, subscriptions renew automatically. You may cancel your subscription with 14 days’ notice through your account settings. No refunds will be issued for already-paid terms unless the Service is unavailable due to an error on our part. For European consumers, the statutory 14-day withdrawal period applies to online purchases.
              </p>

              <h2 className="text-2xl font-semibold">8. Intellectual Property</h2>
              <p>
                The technology, software, and content of the Service remain the property of Disoriti. You retain ownership of the Content you create, but you grant us a limited license to use it for the purpose of providing the Service.
              </p>

              <h2 className="text-2xl font-semibold">9. AI Output and Disclaimers</h2>
              <p>
                The AI-generated content produced by the Service is generated automatically and may contain inaccuracies. You are solely responsible for the use of the generated content and for compliance with applicable laws, including copyright and advertising regulations. We do not guarantee that the Service automatically complies with all laws and regulations in your jurisdiction; it is the User’s responsibility to ensure that the use of the Service complies with local laws.
              </p>

              <h2 className="text-2xl font-semibold">10. Indemnification</h2>
              <p>
                The User indemnifies Disoriti against any third-party claims arising from the use of the Service, including claims related to Content uploaded or generated by the User.
              </p>

              <h2 className="text-2xl font-semibold">11. Termination</h2>
              <p>
                We may suspend or terminate your account if you violate these Terms or misuse the Service. You may terminate your account at any time through your account settings.
              </p>

              <h2 className="text-2xl font-semibold">12. Limitation of Liability</h2>
              <p>
                Our Services are provided “as is” without any warranties. We are not liable for indirect or consequential damages. Our total liability is limited to the amount you have paid us in the past 12 months. We are not liable for interruptions or delays caused by circumstances beyond our control (force majeure).
              </p>

              <h2 className="text-2xl font-semibold">13. Changes</h2>
              <p>
                We may update these Terms from time to time. We will notify you of any significant changes via email or on our website. Continued use of the Service after such changes take effect constitutes acceptance of the updated Terms.
              </p>

              <h2 className="text-2xl font-semibold">14. Governing Law and Disputes</h2>
              <p>
                These Terms are governed by Dutch law. Disputes will be submitted to the competent court in the Netherlands, unless mandatory law in your country provides otherwise. For consumers outside the Netherlands, the mandatory consumer protection laws of their country of residence will apply where required by law.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="relative border-t border-primary/10 mt-24">
        <div className="container mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-muted-foreground text-sm">
              © {new Date().getFullYear()} Disoriti. All rights reserved.
            </div>
            <div className="flex items-center gap-6 text-sm">
              <Link href="/" className="text-muted-foreground hover:text-primary transition-colors">
                Home
              </Link>
              <Link href="/terms" className="text-muted-foreground hover:text-primary transition-colors">
                Terms of Service
              </Link>
              <Link href="#" className="text-muted-foreground hover:text-primary transition-colors">
                Privacy Policy
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
